### ISSUE TITLE
Submitting issues to pages in DOCS

### ISSUE THREAD

**Issue by DEberhardt** [Azure/azure-docs-powershell-azuread#625] opened 2021-06-12 16:56 UTC
From the [DOCs page,](https://docs.microsoft.com/en-us/powershell/module/azuread/open-azureadmsprivilegedroleassignmentrequest?view=azureadps-2.0-preview) one cannot open an issue directly here. 

Is that intentional?

**Comment by msewaweru** [comment] 2021-11-25 13:05
This is by design at the moment. Should this change, I will update you here. Proceeding to close this issue.

**Closed by msewaweru** 2021-11-25 13:05 UTC
