### ISSUE TITLE
Get-AzureAdDirectoryRole does NOT return all roles

### ISSUE THREAD

**Issue by lesterw1** [Azure/azure-docs-powershell-azuread#245] opened 2018-11-30 09:56 UTC
The cmdlet **Get-AzureAdDirectoryRole** does NOT return all available roles. This is inconsistent with other Azure PowerShell cmdlets and should either be fixed or documented accordingly. It *may* be that **Get-AzureAdDirectoryRole** only returns those role names which have been assigned to users. Unintuitively, to get a full list of Azure AD roles, use the cmdlet **Get-AzureAdDirectoryroletemplate**.

The following PowerShell illustrates the issue by listing those roles which **Get-AzureAdDirectoryRole** failed to return:
`Compare-Object (Get-AzureADDirectoryroleTemplate).DisplayName (Get-AzureADDirectoryRole).DisplayName`

**Comment by ricuk** [comment] 2019-04-22 11:42
You have to enable an Azure AD directory role to make it appear in the list returned by Get-AzureADDirectoryRole. For instance, to enable the "Power BI Service Administrator" role:
```
$RoleTemplate = Get-AzureADDirectoryRoleTemplate | Where-Object {$_.DisplayName -eq "Power BI Service Administrator"}
Enable-AzureADDirectoryRole -RoleTemplateId $RoleTemplate.ObjectId
```

**Comment by timothywarner** [comment] 2019-05-14 12:45
What am I missing here, conceptually? Why doesn't Get-AzureADDirectoryRoleTemplate return Global Administrator?

**Comment by devblackops** [comment] 2019-08-10 00:01
@timothywarner You aren't kidding. The help for `Get-AzureADDirectoryRole` makes **no** mention that it only returns enabled roles. If that is the intended behavior, then a `-ListAvailable` switch should be added to the cmdlet. This aligns with how standard PowerShell commands like `Get-Module` work. Providing that switch **should** make `Get-AzureADDirectoryRole` return all roles, regardles if they are enable or not. There should also be a boolean `Enabled` property added to the object `Microsoft.Open.AzureAD.Model.DirectoryRole` that is returned so you can tell which ones are enabled and which ones aren't. That would make the whole UX better.

**Comment by SteloNLD** [comment] 2020-11-25 09:32
This is still an issue as of 25-11-2020

**Comment by billmath** [comment] 2020-12-01 18:48
Hi @lesterw1 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill

**Closed by billmath** 2020-12-01 18:48 UTC

**Comment by PlasmatikSteak** [comment] 2021-06-02 07:22
This is still an issue as of 02-06-2021

**Comment by ranabanerjee15** [comment] 2021-06-10 03:34
> The cmdlet **Get-AzureAdDirectoryRole** does NOT return all available roles. This is inconsistent with other Azure PowerShell cmdlets and should either be fixed or documented accordingly. It _may_ be that **Get-AzureAdDirectoryRole** only returns those role names which have been assigned to users. Unintuitively, to get a full list of Azure AD roles, use the cmdlet **Get-AzureAdDirectoryroletemplate**.
> 
> The following PowerShell illustrates the issue by listing those roles which **Get-AzureAdDirectoryRole** failed to return:
> `Compare-Object (Get-AzureADDirectoryroleTemplate).DisplayName (Get-AzureADDirectoryRole).DisplayName`

Hello Everyone, is the following statement true ?
 **Get-AzureAdDirectoryRole** only returns those role names which have been assigned to users. **

can there be a situation where a role is not "Enabled" and has users assigned to it ?

**Comment by cfcpreilly** [comment] 2021-09-15 17:24
@ranabanerjee15 That statement doesn't appear to be correct. After assigning a member to a role the role becomes enabled. After removing the member the role remains enabled. So I now have an enabled role with no assignments.

**Comment by ranabanerjee15** [comment] 2021-09-16 02:51
@cfcpreilly  I found that the AD role only becomes enabled when any user is assigned to the role. once assigned the role stays enabled even if no users are assigned to it.

**Comment by cfcpreilly** [comment] 2021-09-16 13:14
@ranabanerjee15 That's been my experience too.

**Comment by DavidHomerOxford** [comment] 2021-11-26 16:33
The graph API documentation clarifies this "To read a directory role or update its members, it must first be activated in the tenant." Once it's activated you can't deactivate it. It's quite an odd behaviour and should be documented.
https://docs.microsoft.com/en-us/graph/api/resources/directoryrole?view=graph-rest-1.0

There's also a couple of other weirdnesses I've found.

1. Get-AzureADDirectoryRoleMember gets all members including service principals which matches the Azure portal.

2. The new Microsoft Graph API does *not* return service principals (which conflicts with the Azure portal).

3. The AzureAD PowerShell module (and even the AzureADPreview) does not use the Microsoft Graph API but actually uses the old Azure AD Graph which gets turn off on June 30, 2022 so not sure if they're actually going to update the module or whether it'll just die in 6 months.

Microsoft just doesn't stick to anything, finish anything, or document anything properly when it comes to Azure.


Thanks,


Dave

**Comment by DeanGross** [comment] 2022-03-25 12:00
This should not be closed, the problem still exists. How can a module that has been in production for so long still be sorry poorly implemented? What is going on?

**Comment by mikeblakeuk** [comment] 2022-11-23 15:33
It should throw if the ObjectId passed in is null/empty
For me, I needed "Power BI Administrator" not "Power BI Service Administrator"
