### ISSUE TITLE
Get-AzureADAuditSignInLogs no longer provides granular MFA failure information

### ISSUE THREAD

**Issue by blakebourgeois** [Azure/azure-docs-powershell-azuread#423] opened 2020-06-08 15:23 UTC
Something recently changed with the results Get-AzureADAuditSignInLogs provides for failed sign in attempts.

Up until last week the SignInStatus used to provide details like "Authentication call went to voicemail" or "User hung up phone call without succeeding the authentication attempt" or "Authentication call went to voicemail" etc.

Today, the FailureReason just says authentication failed during strong authentication requests or strong authentication is required. The AdditionalDetails provides a well-written, but generic description of the failure that is not nearly as helpful as the former, more simple errors.

The granular details still exist within the Azure AD Sign-ins log under "Authentication Details" and the "Result detail" column. It doesn't appear to be possible to find this column anywhere within the Get-AzureADAuditSignInLogs result set.

**Comment by billmath** [comment] 2020-09-23 17:06
Hi @blakebourgeois 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  I need to follow up with them and see if this is by design or not.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill

**Closed by billmath** 2020-09-23 17:06 UTC
