### ISSUE TITLE
Get-AzureAdAuditSigninLogs does not retrieve all logs for a user

### ISSUE THREAD

**Issue by benoithamet** [Azure/azure-docs-powershell-azuread#622] opened 2021-06-08 04:33 UTC
Hi there

I'm using the Get-AzureAdAuditSigninLogs to identify users which has not logged for 30 days as part of a script.
Unfortunately Get-AzureAdAuditSigninLogs seems to not using all sign in logs for a user; I have identified users which has not signed in for few days (3, 6 or 8) and they are reporting as not signed in for more than 30 days.
I'm sure this is not my code as I ran the Get-AzureAdAuditSigninLogs for some of these incorrectly identified users and did not get any log
I use the Top 1 filter to get the last entry
Get-AzureAdAuditSigninLogs -top 1 -filter "userprincipalname eq <user UPN>" | select CreatedDateTime

**Comment by jdelforno** [comment] 2022-10-20 05:51
@benoithamet we ran into the same problem. I'd say the issue is less with the PowerShell Module and more with the Azure API it interfaces with tbh.

**Comment by benoithamet** [comment] 2022-10-20 20:53
Hi @jdelforno 
I dont think this is the API because you can get the information in Azure portal, which basically uses the same endpoint than PS to display the information
by the way thanks for your comment as I totally forgot about this and there has been no action from MS 😒

**Comment by msewaweru** [comment] 2023-06-19 09:49
@benoithamet - Apologies that we have not been of much help on this issue. Since the Azure AD Preview module is planned for deprecation, all investments are in the Microsoft Graph PowerShell module. I recommend that you try [Microsoft Graph PowerShell]([url](https://learn.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0)), which is replacing the legacy modules. In Microsoft Graph PowerShell, you can use [Get-MgAuditLogSignIn](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.reports/get-mgauditlogsignin?view=graph-powershell-1.0) cmdlet as the alternative.
If you experience any further issues with this feature, you can try one of the following links for additional help.
Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

I'll proceed to close this issue. Feel free to log any doc-related issues here.

**Closed by msewaweru** 2023-06-19 09:49 UTC
