### ISSUE TITLE
New-AzureADPrivilegedRoleAssignment fails with BadGateway

### ISSUE THREAD

**Issue by grimstoner** [Azure/azure-docs-powershell-azuread#836] opened 2022-06-29 13:27 UTC
I have a PIM-enabled AzureAD group.

When trying to assign this to a user using `New-AzureADPrivilegedRoleAssignment`, it fails with an **UnknownError**:

```
C:> New-AzureADPrivilegedRoleAssignment -RoleId $roleId -UserId $userId
New-AzureADPrivilegedRoleAssignment : Error occurred while executing NewPrivilegedRoleAssignment
Code: UnknownError
Message:
InnerError:
  RequestId: 01c9cacf-8bf0-40b2-afc6-6b1666b0f22d
  DateTimeStamp: Wed, 29 Jun 2022 13:20:57 GMT
HttpStatusCode: BadGateway
HttpStatusDescription: Bad Gateway
HttpResponseStatus: Completed
At line:1 char:1
+ New-AzureADPrivilegedRoleAssignment -RoleId $roleId -UserId $userId
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADPrivilegedRoleAssignment], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.NewPrivilegedRoleAssignment
```

**Comment by msewaweru** [comment] 2022-07-19 07:10
Hi @grimstoner, thanks for highlighting this issue and apologies for the delayed response.

@rkarim-ms, I have been able to reproduce this issue on my end and would appreciate your help to understanding the cause and remedy. Thanks.

**Comment by rkarim-ms** [comment] 2022-08-23 02:18
Hi @grimstoner, thank you again for reaching out and for your patience here.

To confirm our understanding of this scenario, if trying to assign the user to a group using PIM, we don't currently offer any API support for PIM privileged access groups. (background on privileged access groups can be found here: https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/groups-features)

However, if trying to assign the user to an Azure AD role, the **role assignment schedule requests API** can be used to create a new role assignment as follows:
(PowerShell example for an active assignment)
https://docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignmentschedulerequests?view=graph-rest-1.0&tabs=powershell#example-1-admin-assigning-a-directory-role-to-a-principal

(Tutorial for an eligible assignment)
https://docs.microsoft.com/en-us/powershell/microsoftgraph/tutorial-pim?view=graph-powershell-1.0

(PowerShell docs)
https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devicemanagement.enrolment/new-mgrolemanagementdirectoryroleassignmentschedulerequest?view=graph-powershell-1.0

Also adding @mandardalvi for further insight into this issue.

**Comment by msewaweru** [comment] 2022-09-08 08:36
Thanks @rkarim-ms for your feedback.

@grimstoner, I would recommend that try this in Microsoft Graph PowerShell as indicated above. Azure AD and Azure AD Preview modules are headed for deprection and all investments are in Microsoft Graph PowerShell. Get started here: [Overview of Microsoft Graph PowerShell](https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0).

Proceeding to close this issue.

**Closed by msewaweru** 2022-09-08 08:36 UTC
