### ISSUE TITLE
Get-MsolDeviceRegistrationServicePolicy error

### ISSUE THREAD

**Issue by AlyaKoni** [Azure/azure-docs-powershell-azuread#693] opened 2021-08-25 18:47 UTC
Loaded Modules:
MSOnline 1.1.183.57
AzureADPreview 2.0.2.138

Running the cmdlet Get-MsolDeviceRegistrationServicePolicy gives error:
At least one error happened. 

Full trace in german:
Get-MsolDeviceRegistrationServicePolicy : Mindestens ein Fehler ist aufgetreten.
In Zeile:1 Zeichen:1
+ Get-MsolDeviceRegistrationServicePolicy
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Get-MsolDeviceRegistrationServicePolicy], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Online.Administration.Automation.GetDeviceRegistrationServicePoli 
   cy

**Comment by msewaweru** [comment] 2022-01-14 08:54
Hello @AlyaKoni, thanks for your issue submission and apologies for the delayed response.

I'm unable to reproduce this error running the same version on MSOnline module 1.1.183.57.

![image](https://user-images.githubusercontent.com/73849846/149486947-9df6f515-3e09-48db-b237-0d43f7baddcf.png)

Please redo this and let me know. I will proceed to close this issue. Feel free to reopen it with any follow up comments. Thanks.

**Closed by msewaweru** 2022-01-14 08:54 UTC

**Comment by AlyaKoni** [comment] 2022-01-14 14:57
Problem still exists. Please reopen!

 

PS C:\Users\konrad.brunner> Get-MsolDeviceRegistrationServicePolicy

Get-MsolDeviceRegistrationServicePolicy : Mindestens ein Fehler ist
aufgetreten.

In Zeile:1 Zeichen:1

+ Get-MsolDeviceRegistrationServicePolicy

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : OperationStopped: (:)
[Get-MsolDeviceRegistrationServicePolicy], AggregateException

    + FullyQualifiedErrorId :
System.AggregateException,Microsoft.Online.Administration.Automation.GetDevi
ceRegistrationServi 

   cePolicy 

 

 

 

Herzliche Grüsse / Kind regards

Koni / Konrad Brunner

 

Alya Consulting
Wir sind Cloud

 

Von: Eunice Waweru ***@***.***> 
Gesendet: Freitag, 14. Januar 2022 09:55
An: Azure/azure-docs-powershell-azuread
***@***.***>
Cc: Konrad Brunner ***@***.***>; Mention
***@***.***>
Betreff: Re: [Azure/azure-docs-powershell-azuread]
Get-MsolDeviceRegistrationServicePolicy error (#693)

 

Closed #693
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FAzure%2Fazure-docs-powershell-azuread%2Fissues%2F693&data=04%7C01%7Ckonr
ad.brunner%40alyaconsulting.ch%7Cb787f11e5ded4b25fd3f08d9d73b8c7d%7C5757de31
29c44f399bd1478cec348035%7C1%7C0%7C637777473024760927%7CUnknown%7CTWFpbGZsb3
d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&
sdata=ngY4jzx%2F5U7bbvw8ko7EEP%2FU%2Ft3erCr%2BuKRXmGBkF9I%3D&reserved=0> .


Reply to this email directly, view it on GitHub
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FAzure%2Fazure-docs-powershell-azuread%2Fissues%2F693%23event-5893303093&
data=04%7C01%7Ckonrad.brunner%40alyaconsulting.ch%7Cb787f11e5ded4b25fd3f08d9
d73b8c7d%7C5757de3129c44f399bd1478cec348035%7C1%7C0%7C637777473024770889%7CU
nknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJ
XVCI6Mn0%3D%7C3000&sdata=TiErWPjyhU2ssD23Oqn5LOGVQk3a7vXiUq16qQi26jE%3D&rese
rved=0> , or unsubscribe
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fnotifications%2Funsubscribe-auth%2FAOEVSQUSBLDBAVQWJ32ICI3UV7QGHANCNFSM5
CZXT2LQ&data=04%7C01%7Ckonrad.brunner%40alyaconsulting.ch%7Cb787f11e5ded4b25
fd3f08d9d73b8c7d%7C5757de3129c44f399bd1478cec348035%7C1%7C0%7C63777747302478
0839%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1
haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Mzy69wSvDi6ylVagivrNX0ypqv32ExfoyIVwW1TkSyc
%3D&reserved=0> .
Triage notifications on the go with GitHub Mobile for iOS
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.appl
e.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%
26pt%3D524675&data=04%7C01%7Ckonrad.brunner%40alyaconsulting.ch%7Cb787f11e5d
ed4b25fd3f08d9d73b8c7d%7C5757de3129c44f399bd1478cec348035%7C1%7C0%7C63777747
3024780839%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBT
iI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YEwBS%2F1i7TiNXVebFf86doYKDFsQeqrXm6R
ev6M5vGc%3D&reserved=0>  or Android. 
You are receiving this because you were mentioned.
<https://github.com/notifications/beacon/AOEVSQWHW2LDGEFFHS473XTUV7QGHA5CNFS
M5CZXT2L2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZL
OORPWSZGPAAAAAAK7ISVTK.gif> Message ID:
***@***.***
.com
<mailto:Azure/azure-docs-powershell-azuread/issue/693/issue_event/5893303093
@github.com> >

**Comment by AlyaKoni** [comment] 2022-01-14 15:22
Looks like the way how you login plays a role. Here an example script to
reproduce:

 

Connect-AzAccount

$AlyaContext = Get-AzContext

$graphToken =
[Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.Auth
enticationFactory.Authenticate($AlyaContext.Account,
$AlyaContext.Environment, $AlyaContext.Tenant.Id, $null, "Never", $null,
https://graph.microsoft.com).AccessToken

$aadToken =
[Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.Auth
enticationFactory.Authenticate($AlyaContext.Account,
$AlyaContext.Environment, $AlyaContext.Tenant.Id, $null, "Never", $null,
https://graph.windows.net).AccessToken

 

Connect-AzureAD -AadAccessToken $aadToken -MsAccessToken $graphToken
-AccountId $AlyaContext.Account.Id -TenantId $AlyaContext.tenant.id
-AzureEnvironmentName $AlyaContext.Environment.Name

Connect-MsolService -AdGraphAccessToken $aadToken -MsGraphAccessToken
$graphToken -AzureEnvironment $AlyaContext.Environment.Name

 

Get-MsolUser -MaxResults 5 -> Works

Get-MsolDeviceRegistrationServicePolicy -> Error

 

 

Herzliche Grüsse / Kind regards

Koni / Konrad Brunner

 

Alya Consulting
Wir sind Cloud

 

Von: Eunice Waweru ***@***.***> 
Gesendet: Freitag, 14. Januar 2022 09:55
An: Azure/azure-docs-powershell-azuread
***@***.***>
Cc: Konrad Brunner ***@***.***>; Mention
***@***.***>
Betreff: Re: [Azure/azure-docs-powershell-azuread]
Get-MsolDeviceRegistrationServicePolicy error (#693)

 

Closed #693
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FAzure%2Fazure-docs-powershell-azuread%2Fissues%2F693&data=04%7C01%7Ckonr
ad.brunner%40alyaconsulting.ch%7Cb787f11e5ded4b25fd3f08d9d73b8c7d%7C5757de31
29c44f399bd1478cec348035%7C1%7C0%7C637777473024760927%7CUnknown%7CTWFpbGZsb3
d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&
sdata=ngY4jzx%2F5U7bbvw8ko7EEP%2FU%2Ft3erCr%2BuKRXmGBkF9I%3D&reserved=0> .


Reply to this email directly, view it on GitHub
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FAzure%2Fazure-docs-powershell-azuread%2Fissues%2F693%23event-5893303093&
data=04%7C01%7Ckonrad.brunner%40alyaconsulting.ch%7Cb787f11e5ded4b25fd3f08d9
d73b8c7d%7C5757de3129c44f399bd1478cec348035%7C1%7C0%7C637777473024770889%7CU
nknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJ
XVCI6Mn0%3D%7C3000&sdata=TiErWPjyhU2ssD23Oqn5LOGVQk3a7vXiUq16qQi26jE%3D&rese
rved=0> , or unsubscribe
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fnotifications%2Funsubscribe-auth%2FAOEVSQUSBLDBAVQWJ32ICI3UV7QGHANCNFSM5
CZXT2LQ&data=04%7C01%7Ckonrad.brunner%40alyaconsulting.ch%7Cb787f11e5ded4b25
fd3f08d9d73b8c7d%7C5757de3129c44f399bd1478cec348035%7C1%7C0%7C63777747302478
0839%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1
haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Mzy69wSvDi6ylVagivrNX0ypqv32ExfoyIVwW1TkSyc
%3D&reserved=0> .
Triage notifications on the go with GitHub Mobile for iOS
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.appl
e.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%
26pt%3D524675&data=04%7C01%7Ckonrad.brunner%40alyaconsulting.ch%7Cb787f11e5d
ed4b25fd3f08d9d73b8c7d%7C5757de3129c44f399bd1478cec348035%7C1%7C0%7C63777747
3024780839%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBT
iI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YEwBS%2F1i7TiNXVebFf86doYKDFsQeqrXm6R
ev6M5vGc%3D&reserved=0>  or Android. 
You are receiving this because you were mentioned.
<https://github.com/notifications/beacon/AOEVSQWHW2LDGEFFHS473XTUV7QGHA5CNFS
M5CZXT2L2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZL
OORPWSZGPAAAAAAK7ISVTK.gif> Message ID:
***@***.***
.com
<mailto:Azure/azure-docs-powershell-azuread/issue/693/issue_event/5893303093
@github.com> >
